CREATE TABLE t_admin(
	id INT not null AUTO_INCREMENT,
	userName VARCHAR(20) NOT NULL,
	userPassword VARCHAR(20) NOT NULL,
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


INSERT INTO t_admin VALUES(NULL,'唐三','123456');
INSERT INTO t_admin VALUES(NULL,'沐白','123456');
INSERT INTO t_admin VALUES(NULL,'竹清','123456');
INSERT INTO t_admin VALUES(1,'aaa','123456');
