CREATE TABLE t_chefei(
	id INT not null AUTO_INCREMENT,
	hao VARCHAR(20) NOT NULL,
	jdate VARCHAR(20) NOT NULL,
	ldate VARCHAR(20) NOT NULL,
	cost INT NOT NULL,
	adate VARCHAR(20) NOT NULL,
	hours INT NOT NULL,
	price INT NOT NULL,
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
