CREATE TABLE t_che(
	id INT not null AUTO_INCREMENT,
	hao VARCHAR(20) NOT NULL,
	leixing VARCHAR(20) NOT NULL,
	picture VARCHAR(20) NOT NULL,
	info VARCHAR(20) NOT NULL,
	uid INT NOT NULL,
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
