CREATE TABLE t_userinfo(
	id INT not null AUTO_INCREMENT,
	username VARCHAR(20) NOT NULL,
	pwd VARCHAR(20) NOT NULL,
	age INT NOT NULL,
	tel VARCHAR(20) NOT NULL,
	money INT NOT NULL,
	PRIMARY KEY(id)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
